<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KNODTNC" name="Default test" tests="5" failures="1" timestamp="23 Aug 2020 02:45:57 GMT" time="30.006" errors="0">
  <testcase name="@AfterMethod close" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at PracticesBYTestNG.TestNGDataProvider.close(TestNGDataProvider.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- @AfterMethod close -->
  <testcase name="@BeforeMethod startUp" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod startUp -->
  <testcase name="@AfterMethod close" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod close -->
  <testcase name="@BeforeMethod startUp" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod startUp -->
  <testcase name="@AfterMethod close" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod close -->
  <testcase name="@BeforeMethod startUp" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod startUp -->
  <testcase name="@AfterMethod close" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod close -->
  <testcase name="@BeforeMethod startUp" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @BeforeMethod startUp -->
  <testcase name="@AfterMethod close" time="0.0" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- @AfterMethod close -->
  <testcase name="loginPage" time="0.065" classname="PracticesBYTestNG.TestNGDataProvider">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at PracticesBYTestNG.TestNGDataProvider.loginPage(TestNGDataProvider.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- loginPage -->
  <testcase name="loginPage" time="0.001" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- loginPage -->
  <testcase name="loginPage" time="0.002" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- loginPage -->
  <testcase name="loginPage" time="0.001" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- loginPage -->
  <testcase name="loginPage" time="0.001" classname="PracticesBYTestNG.TestNGDataProvider">
    <skipped/>
  </testcase> <!-- loginPage -->
</testsuite> <!-- Default test -->
